export const ACTION_TYPE = {
	SET_USER: "SET_USER",
	LOGOUT: "LOGOUT",
	SET_EDITING_PRODUCT: "SET_EDITING_PRODUCT",
	OPEN_MODAL: "OPEN_MODAL",
	CLOSE_MODAL: "CLOSE_MODAL",
	SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
	SET_PRODUCT_IN_BASKET: "SET_PRODUCT_IN_BASKET",
	DELETE_PRODUCT_IN_BASKET: "DELETE_PRODUCT_IN_BASKET",
	CLEARE_BASKET: "CLEARE_BASKET",
};
